# Generated by Django 5.0.6 on 2024-06-27 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_table_event_image_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_table',
            name='event_image_location',
        ),
        migrations.CreateModel(
            name='Event_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_image_location', models.ImageField(blank=True, null=True, upload_to='event/static')),
                ('event_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='event.event_table')),
            ],
        ),
    ]
