# Generated by Django 5.0.6 on 2024-05-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('creator_id', models.IntegerField(null=True)),
                ('last_user_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField(null=True)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('doj', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('height', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('standard_id', models.IntegerField(null=True)),
                ('creator_id', models.IntegerField(null=True)),
                ('last_user_id', models.IntegerField(null=True)),
                ('is_active', models.IntegerField(null=True)),
                ('session', models.CharField(max_length=255)),
                ('photo_location', models.CharField(max_length=255)),
            ],
        ),
    ]
