# Generated by Django 5.0.6 on 2024-05-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='award_winners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('game_won_id', models.IntegerField()),
                ('date', models.DateField()),
                ('level', models.CharField(max_length=200)),
                ('medal_type', models.CharField(max_length=200)),
                ('achivements', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_game', models.CharField(max_length=200)),
                ('type_of_game', models.CharField(max_length=200)),
            ],
        ),
    ]
