# Generated by Django 5.0.6 on 2024-05-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(null=True)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField()),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField(null=True)),
                ('schedule_order', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField(null=True)),
                ('class_teacher', models.CharField(max_length=255)),
                ('monitor_student_id', models.IntegerField(null=True)),
            ],
        ),
    ]
